dist: trusty
sudo: false
language: cpp

install:
  - |
    BOOST_VERSION=1.66.0
    BOOST_URL="https://dl.bintray.com/boostorg/release/${BOOST_VERSION}/source/boost_${BOOST_VERSION//\./_}.tar.gz"
      mkdir -p ${BOOST_DIR}
      { travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
    CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"

script:
  - cmake .
  - cmake --build . -- -j2
  - ctest